### ISSUE TITLE
redesign main page to take into account multiple categories of lessons and sources

### ISSUE THREAD

**Issue by ohasselblad** [CartoDB/academy#155]
We are experimenting with different lesson formats and soon will be releasing an 'academy lite' lesson that doesn't fit into the structure of Academy right now.

I'd like to temporarily change the page (http://academy.cartodb.com/index.html) to have two types of courses

* Long-form -- everything that's already there
* Short-form -- the new lesson that we are about to put up

@andrewxhill @matallo what do you think?

**Comment by matallo** [comment]
awesome, we can place them just above/below the current section, even the same style and have a `lite: true` in the info block :)

**Comment by ohasselblad** [comment]
Great :) Could we place it below?

Something like:

## Our Courses

### Long-form 
* Introduction to Mapping
* Desgin
* SQL
* CartoDB.js
* Etc.

### Short-form
* CartoCSS
* SQL
* JavaScript
* Design
* Special Skills
* Etc.

**Comment by ohasselblad** [comment]
@saleiva we're expecting a good amount of new content on academy this month. the biggest change will be shorter lessons (5 minutes long, short amount of text) that are different from normal academy lessons. we want http://academy.cartodb.com to be in two sections (as you can see above).

**Comment by saleiva** [comment]
I propose we update the content, and then we do this :)

**Comment by ohasselblad** [comment]
Ok! This lesson was added in #168. We have it temporarily in a new container, but with academy reorg we're going to need a new organization structure.

@saleiva @matallo could we implement something like long form/short form as above?

**Comment by ohasselblad** [comment]
With #178 we need further changes inline with what was requested above... We now have two main categories: 1. CartoDB-created lessons (long form and short form) 2. Community-contributed lessons (hosted here, linked to elsewhere)

**Comment by ztephm** [comment]
other format suggestions 
cc: @ohasselblad 

1. MAKE IT RESPONSIVE
  + reason = so on smaller resolution the green Our Courses boxes stack
2. CREATE BEGINNER/INTERMEDIATE/ADVANCED SECTIONS FOR OUR COURSES SECTION
  + reason =  since we're adding a lot more lessons, would be useful for users to have a shorter way to browse than reading lesson titles
  + example: Beginner section could include Online Mapping for Beginners and Introduction to Map Design
3. ADD EXTERNAL REFERENCES SECTION TO MAIN COURSE PAGE
  + under or next to Prerequisites? Up to designers of course but list of external references links is secondary in importance to What you'll learn and Prerequisites.

**Comment by andrewxhill** [comment]
perhaps we should capture this all in the wiki page under a section Redesign? 
https://github.com/CartoDB/cartodb-management/wiki/Academy-Roadmap

**Comment by carlostallon** [comment]
will be done with the new academy design
