### ISSUE TITLE
Intermediate design: Lesson 1

### ISSUE THREAD

**Issue by ohasselblad** [CartoDB/academy#160]

**Comment by ohasselblad** [comment]
Hey @ztephm what direction do you think you'll go in for this? Could you outline it?

**Comment by ztephm** [comment]
Hi, thinking 
Lesson 1 = when to use certain kind of map
Lesson 2 = Typography in Cartography
Lesson 3 = Color in Cartography
(Lesson 2 & 3 would flesh out areas we said that we're not getting into yet in other Map Acad. lessons)

Lesson 1:
[Feel like I need to do more research on pros/cons, ie: of Intensity Maps, what are drawbacks? Let me know if u have any good resources]

WHAT KIND OF MAP TO USE WHEN:
- Simple
point = shows location only
polygon = shows location & total area
- Cluster
for point marker maps only
one point marker represents an aggregation of multiple point markers in a given pixel area. A number representing the amount of markers being aggregated is shown within the marker, and the size of the marker increases as the amount of markers aggregated increases.
explain how # of buckets effects aggregation area size
do we use grid-based or distance-based clustering? https://developers.google.com/maps/articles/toomanymarkers
looks similar to Bubble Map but:
bubble is a marker that represents one point, not an aggregation of points.
bigger bubble marker = larger data attribute number, not larger amount of aggregated markers in an area
- Choropleth
for points or polygons
dataset must contain numerical column to base choropleth on
uses color to illustrate differences in a range of data.
must be normalized
never use for “counts” = ie: number of people
use for rates = ie: number of people per square mile
Explain Quantification
Mention composite operations & link out
Possible issue: smaller-sized polygons can be overlooked relative to large ones
- Category
combined with other types of maps listed here (ie: like Simple)
use color or images to differentiate single dataset column values 
you can do this w/CartoCSS instead of wizard (test out max # of categories)
- Bubble
Also called proportional symbol map
Scale the location’s marker size based on a numerical data attribute.
Show how Quantification effects symbol size: ie Larger bubbles w/Quantile turn into same-size bubbles w/Equal Interval, etc based on dataset numbers.
Can use counts (doesn’t have to be normalized)
Possible issue: visually users don’t estimate size well in comparison, even with legend
- Heatmap
Layers and blends markers so that areas of “hotter” color (default = red) represent an aggregation of larger numbers of individual markers within a certain pixel area. Areas with a smaller density of points have a lighter color.
Besides changing marker size & opacity, you can edit these colors in CartoCSS
You are able to animate this in our wizard
Possible issue: gradient effect can obscure detail (& data is being invented for areas between original points) 
- Intensity:
layers individual points (representing actual locations, not aggregations) and automatically uses a composite mode to have colors change in areas of higher point density
similar to heatmap
- Density:
When you color by polygon, because of the size difference of polygons the meaning of data can be distorted
example: election map where winning party is shown by state. Dems won 50% of the vote overall, while Reps won 50% of the vote overall. This might not be visible, b/c larger state polygons would visually look more dominant than smaller state polygons. Hexagon density takes care of this by not adhering to polygon shape since each hexagon is of the same area size.
- Torque/Torque Heat/Torque Cat
aggregates spatially & also by time
explain that time is taken as one unit from starting value in date column to ending value, then divided into bins
give formula for calculating number of steps needed from Support Bee

**Comment by ztephm** [comment]
Hi @ohasselblad testing out the work-in-progress label, thanks! ref: https://github.com/CartoDB/academy/pull/174
