### ISSUE TITLE
Which Mailchimp account are we using? 

### ISSUE THREAD

**Issue by furilo** [CartoDB/academy#44]
Matallo I was testing the subscribe widgets and ... 

![image](https://cloud.githubusercontent.com/assets/24740/2907952/e8d245c2-d621-11e3-9baf-fe3414c9f8bf.png)

Do we have to change the account? 

cc @saleiva once this is fixed we are free to release

**Comment by matallo** [comment]
@vuxita for every course we use a separate mailchimp_id, do you want to review them?

**Comment by inigomedina** [comment]
I’m closing this issue because it has been inactive for a long time. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue.

Thank you!
